spring.application.name=PhongTro
spring.datasource.url=jdbc:mysql://localhost:3306/qlphongtro
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true